version: '3.9'

# Run: docker-compose -p db-course up

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: my-project-template
    ports:
      - 5432:5432

  adminer:
    image: adminer:4.8.1
    restart: unless-stopped
    ports:
      - 8080:8080
